### ISSUE TITLE
Google Drive not accessible

### ISSUE THREAD

**Issue by MaxGonzalezSaez-Diez** [owenzlz/EgoHOS#10]
It seems like the google drive is not accessible. I am not able to download the weights/images etc and get an error when I try to open the drive. Would it be possible to fix this?

**Comment by owenzlz** [comment]
Hi, my school account gets deactivated after graduation, so gdrive is not longer accessible. I am uploading the files to somewhere else, and will get back to you with a new link later (hopefully today).

**Comment by ZhaofengSHI** [comment]
Hi, has the new link been uploaded yet?

**Comment by qiaomu-miao** [comment]
Hello, may I know if the new link has been set up?

**Comment by owenzlz** [comment]
Hi guys, the links have been updated. Please let me know if there's any access issue.

**Comment by ZhaofengSHI** [comment]
> Hi guys, the links have been updated. Please let me know if there's any access issue.

thank you!!!
